app.name=RedisFX
app.release=preview/beta-3.x
app.doc=https://redisfx.tanh.site
app.homepage=https://github.com/tanhuang2016/RedisFX
app.homepage2=https://gitee.com/tanhuang2016/RedisFX
app.properties=https://raw.githubusercontent.com/tanhuang2016/RedisFX/preview/beta-3.x/rdm-ui/src/main/resources/application.properties
app.properties2=https://gitee.com/tanhuang2016/RedisFX/raw/preview/beta-3.x/rdm-ui/src/main/resources/application.properties
app.version=3.0.0-beta
app.updates[0]=1.\u7CFB\u7EDF\u6807\u9898\u680F\u7EDF\u4E00\u914D\u8272
app.updates[1]=
app.updates[2]=
app.updates[3]=
app.updates[4]=
app.updates[5]=
app.updates[6]=
app.updates[7]=
app.updates[8]=
app.updates[9]=



